services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
      MYSQL_USER: gpicardi
      MYSQL_PASSWORD: bank787878
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'
